### PR TITLE
Manually dispatch events for connected, unassigned targets.

### LINKED ISSUE #95: [ShadyDOM] Cannot listen for events from unslotted Light DOM children
### Description

Events dispatched from Light DOM children cannot be handled unless they are distributed in a `slot`.

#### Live Demo

https://stackblitz.com/edit/shady-dom-events-no-slot

#### Steps to Reproduce

1. Create two elements and nest one in the other.
   * Do not add a `<slot>`
1. Have the child dispatch an event
1. Have the parent listen for that event

#### Expected Results
The event should be handled by the parent.

#### Actual Results
In polyfilled browsers the parent element never receives the event.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- webcomponents: v2.2.7

### PR DESCRIPTION
**Pull request by bicknellr**
This PR causes Shady DOM to manually dispatch all events with targets that are disconnected in the real tree. This causes events to propagate correctly if their path is split between connected and disconnected trees (in the real tree), which can happen if the target (or one of its ancestors) is connected but not assigned to a slot (in the user-facing tree).

~~- [ ] Merge Polymer/polymer#5663~~ (Assuming this passes internal tests, we're considering this low-risk enough to not require that Polymer's `...-changed` events go through this path.)

Fixes #95.

### CODE REVIEW

File: packages/shadydom/src/patch-events.js [hunk 1]
```diff
@@ -391,7 +394,14 @@ function targetNeedsPathCheck(node) {
 /** @this {Node} */
 export function dispatchEvent(event) {
   flush();
-  return this[utils.NATIVE_PREFIX + 'dispatchEvent'](event);
+  if (this instanceof Node && !document.documentElement[utils.NATIVE_PREFIX + 'contains'](this)) {
```
Comment (bicknellr) [inline packages/shadydom/src/patch-events.js:397]: The `this instanceof Node` check here is not something I tried in the perf tests: I hadn't considered non-Node event targets and Node's `contains` throws if you pass it a non-Node.

File: packages/shadydom/src/patch-events.js [hunk 2]
```diff
@@ -305,7 +305,7 @@ function fireHandlers(event, node, phase) {
   }
 }
 
-function retargetNonBubblingEvent(e) {
+function shadyDispatchEvent(e) {
```
Comment (bicknellr) [inline packages/shadydom/src/patch-events.js:308]: Maybe needs bikeshedding, the non-bubbling part of `retargetNonBubblingEvent` isn't correct anymore though.

File: packages/shadydom/src/patch-events.js [hunk 3]
```diff
@@ -508,12 +518,12 @@ export function addEventListener(type, fnOrObj, optionsOrCapture) {
...
-    this.__handlers[type] = this.__handlers[type] ||
-      {'capture': [], 'bubble': []};
-    this.__handlers[type][capture ? 'capture' : 'bubble'].push(wrapperFn);
-  } else {
+  this.__handlers = this.__handlers || {};
+  this.__handlers[type] = this.__handlers[type] ||
+    {'capture': [], 'bubble': []};
+  this.__handlers[type][capture ? 'capture' : 'bubble'].push(wrapperFn);
+
+  if (!nonBubblingEventsToRetarget[type]) {
```
Comment (bicknellr) [inline packages/shadydom/src/patch-events.js:526]: These changes cause _all_ event listeners to be manually added to `__handlers` so that `shadyDispatchEvent` can run them itself. Before, it was just things in `nonBubblingEventsToRetarget` (`focus`, `blur`).

Comment (sorvell) [reply packages/shadydom/src/patch-events.js:526]: This was unexpected for me since I know we have to keep track of the handlers for `removeEventListener`. However, there we keep a map of wrapper function to node/options and here we need the reverse map from node to wrapper function.

File: packages/tests/shadydom/event-path.html [hunk 4]
```diff
@@ -930,6 +937,22 @@
       w.dispatchEvent(new Event('foo'));
       assert.isTrue(heardEvent);
     });
+
+    test('events dispatched to unassigned slottables bubble through the tree above them', () => {
```
Comment (sorvell) [inline packages/tests/shadydom/event-path.html:941]: Let's include a test like the example in this issue: https://github.com/Polymer/lit-element/issues/658.

File: packages/shadydom/src/patch-events.js [hunk 5]
```diff
@@ -327,22 +327,25 @@ function retargetNonBubblingEvent(e) {
...
-    if (i === 0 || (root && root === lastFiredRoot)) {
-      fireHandlers(e, node, 'bubble');
-      // don't bother with window, it doesn't have `getRootNode` and will be last in the path anyway
-      if (node !== window) {
-        lastFiredRoot = node[utils.SHADY_PREFIX + 'getRootNode']();
-      }
-      if (e.__propagationStopped) {
-        return;
-      }
+    if (!(i === 0 || (root && root === lastFiredRoot)) && !bubbles) {
```
[the remark this answers is not in the document]
Comment (bicknellr) [reply packages/shadydom/src/patch-events.js:338]: This is meant to handle composed, non-bubbling events: it's deciding if it should call listeners on `node` using `root && root === lastFiredRoot` to figure out if `node` hosts the last shadow root in which a listener was called, which ends up calling listeners on only the deepest nodes in each shadow root in the path (and `i === 0` handles when `node` is the real target).

This section is confusing and took me a while to realize what was happening when I initially came across it. (Especially this condition, which I haven't helped.) I'll try to rearrange it to make it clearer.

File: packages/shadydom/src/patch-events.js [hunk 6]
```diff
@@ -391,7 +394,14 @@ function targetNeedsPathCheck(node) {
 /** @this {Node} */
 export function dispatchEvent(event) {
   flush();
-  return this[utils.NATIVE_PREFIX + 'dispatchEvent'](event);
+  if (this instanceof Node && !(this === document || document.documentElement[utils.NATIVE_PREFIX + 'contains'](this))) {
```
[the remark this answers is not in the document]
Comment (dfreedm) [reply packages/shadydom/src/patch-events.js:397]: `document.contains` is an O(1) check at least in Chrome, vs a O(height of tree) for other nodes

File: packages/shadydom/src/patch-events.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (bicknellr) [reply packages/shadydom/src/patch-events.js:338]: This has a bug: it always should fire if `i === 0`.

File: packages/shadydom/src/patch-events.js [hunk 7]
```diff
@@ -572,8 +582,8 @@ const EventPatchesDescriptors = utils.getOwnPropertyDescriptors(EventPatches);
 const SHADY_PROTO = '__shady_patchedProto';
 const SHADY_SOURCE_PROTO = '__shady_sourceProto';
 
-function patchEvent(event) {
-  event['__target'] = event.target;
+function patchEvent(event, forcedTarget = undefined) {
+  event['__target'] = forcedTarget !== undefined ? forcedTarget : event.target;
```
Comment (bicknellr) [inline packages/shadydom/src/patch-events.js:586]:
```suggestion
function patchEvent(event, target = event.target) {
  event['__target'] = target;
```
I need to double check that parameter defaults can refer to earlier parameters but this would be clearer if so.

Comment (bicknellr) [reply packages/shadydom/src/patch-events.js]: Added.

File: packages/shadydom/src/patch-events.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (bicknellr) [reply packages/shadydom/src/patch-events.js]: Ok, this check now runs through a function that tries `document.contains` before `document.documentElement.contains`. Should I still benchmark this?

File: packages/shadydom/src/patch-events.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (bicknellr) [reply packages/shadydom/src/patch-events.js]: Updated, PTAL

File: packages/tests/shadydom/event-path.html (hunk 4 above)
Comment (bicknellr) [reply packages/tests/shadydom/event-path.html]: I still need to do this.

File: packages/shadydom/src/patch-events.js [hunk 8]
```diff
@@ -324,17 +324,22 @@ function retargetNonBubblingEvent(e) {
...
   for (let i = 0; i < path.length; i++) {
     node = path[i];
     const nodeData = shadyDataForNode(node);
     const root = nodeData && nodeData.root;
-    if (i === 0 || (root && root === lastFiredRoot)) {
+    // Listeners on the deepest node in the path and the deepest node in each
+    // root of all nodes in the path should be called in the AT_TARGET phase.
+    const atDeepestNodeInRoot = i === 0 || (root && root === lastFiredRoot);
+    if (bubbles || atDeepestNodeInRoot) {
+      eventPhase = atDeepestNodeInRoot ? Event.AT_TARGET : Event.BUBBLING_PHASE;
```
Comment (bicknellr) [inline packages/shadydom/src/patch-events.js:342]: This needs to happen during capturing also...

File: packages/tests/shadydom/event-path.html (hunk 4 above)
Comment (bicknellr) [reply packages/tests/shadydom/event-path.html]: I added another test that I think is closer to what's happening in that bug. I think the reason I was struggling to come up with a scenario that worked for this without including LitElement itself in the tests was that LitElement actually schedules its first render asynchronously after the first `connectedCallback` but I was under the impression that it was sync during `connectedCallback`. The test I added includes a parent and child, where the parent creates an empty shadow root for itself in its constructor and the child dispatches the event in its constructor (tighter timing than the example in the bug), but I simplified by making the parent never actually fill the shadow root with any content. In LitElement, this happens late enough that I think it doesn't strike me as useful to include in the test: the `connectedCallback` dispatching the event happens sync inside an `innerHTML` set in the test (which is all we care about observing) so there's no need to actually make the child appear in the real tree, AFAICT.

File: packages/shadydom/src/patch-events.js (hunk 8 above)
Comment (bicknellr) [reply packages/shadydom/src/patch-events.js]: This is fixed.

File: packages/tests/shadydom/event-path.html [hunk 9]
```diff
@@ -930,6 +937,123 @@
...
+            ShadyDOM.wrap(this).addEventListener('some-event', () => {
+              this.listenerCallCount++;
+            });
+          }
+        });
+
+        customElements.define('child-dispatcher-element', class extends HTMLElement {
+          constructor() {
+            super();
+            ShadyDOM.wrap(this).dispatchEvent(new Event('some-event', {bubbles: true}));
```
Comment (bicknellr) [inline packages/tests/shadydom/event-path.html:1038]: Using `wrap` instead of `wrapIfNeeded` here was necessary to make this test pass. Should I add `dispatchEvent` to the notes for `wrapIfNeeded`?

https://github.com/webcomponents/polyfills/blob/de5c30c3a51e0890bbecf6dc44b5e8364201730a/packages/shadydom/src/shadydom.js#L83-L93

File: packages/shadydom/src/patch-events.js (hunk 1 above)
Comment (bicknellr) [reply packages/shadydom/src/patch-events.js]: We talked about this in a meeting and decided `this instanceof Node` shouldn't be a perf problem and there's another thread about `document.contains` vs `document.documentElement.contains` below so I'm going to close this one.

File: packages/shadydom/src/patch-events.js [hunk 10]
```diff
@@ -306,48 +306,50 @@ function fireHandlers(event, node, phase) {
...
-    fireHandlers(e, node, 'bubble');
-    // don't bother with window, it doesn't have `getRootNode` and will be last in the path anyway
-    if (node !== window) {
-      lastFiredRoot = node[utils.SHADY_PREFIX + 'getRootNode']();
-    }
-    if (e.__propagationStopped) {
-      return;
+    currentTarget = path[i];
+    const atTarget = currentTarget === retargetedPath[i];
+    if (atTarget || bubbles) {
```
Comment (sorvell) [inline packages/shadydom/src/patch-events.js:342]: Can this loop be broken out of when `atTarget` and `bubbles` are false?

File: packages/shadydom/src/utils.js [hunk 11]
```diff
@@ -92,7 +92,14 @@ export const microtask = (callback) => {
   twiddle.textContent = content++;
 }
 
-export const hasDocumentContains = Boolean(document.contains);
+const hasDocumentContains = Boolean(document.contains);
+
+/** @type {function(!Document, !Node): boolean} */
+export const documentContains = (doc, node) => (
+  doc === node ||
+  (hasDocumentContains && doc[NATIVE_PREFIX + 'contains'](node)) ||
```
Comment (sorvell) [inline packages/shadydom/src/utils.js:100]: Suggest doing this check once and writing different `documentContains` implementations based on the result.

File: packages/tests/shadydom/event-path.html [hunk 12]
```diff
@@ -938,20 +938,121 @@
...
+        ShadyDOM.wrap(innerNoSlot).appendChild(target);
+
+        assert.strictEqual(ShadyDOM.wrap(target).assignedSlot, null);
+
+        const eventLog = [];
+        const pushToEventLog = (e) => {
+          eventLog.push({currentTarget: e.currentTarget, eventPhase: e.eventPhase});
+        };
+
+        // `ShadyDOM.wrapIfNeeded(outerNoSlot).shadowRoot` will also see this event in its path,
```
Comment (sorvell) [inline packages/tests/shadydom/event-path.html:988]: Do we have enough information to correct this?

File: packages/tests/shadydom/event-path.html (hunk 9 above)
Comment (sorvell) [reply packages/tests/shadydom/event-path.html:1038]: Yes, that sounds good.

File: packages/shadydom/src/patch-events.js (hunk 2 above)
Comment (sorvell) [reply packages/shadydom/src/patch-events.js:308]: Got it.

File: packages/tests/shadydom/event-path.html [hunk 13]
```diff
@@ -930,6 +937,123 @@
       w.dispatchEvent(new Event('foo'));
       assert.isTrue(heardEvent);
     });
+
+    suite('unassigned slottable targets', () => {
```
Comment (sorvell) [inline packages/tests/shadydom/event-path.html:941]: Suggest adding tests that stress this code path (if we don't have them) for:
1. events that bubble v. not
2. events that are composed v. not
3. events are not sent to removed event listeners

File: packages/shadydom/src/utils.js (hunk 11 above)
Comment (bicknellr) [reply packages/shadydom/src/utils.js:100]: Yeah, that's good idea. Also, I just realized that I was trying to be too clever here with the short-circuiting: if `document.contains` and `document.documentElement` both exist but `doc` doesn't contain `node`, then it will end up running both `contains` calls.

File: packages/shadydom/src/patch-events.js (hunk 10 above)
Comment (bicknellr) [reply packages/shadydom/src/patch-events.js:342]: Not always: if the event is non-bubbling, composed, and dispatched to an element in a shadow root, then both the real target and the shadow root host will see `atTarget` as true even though there are other items in `path` between them.

File: packages/tests/shadydom/event-path.html (hunk 13 above)
Comment (bicknellr) [reply packages/tests/shadydom/event-path.html:952]: Added. Also, good call, the listeners weren't being removed properly.

File: packages/shadydom/src/utils.js (hunk 11 above)
Comment (bicknellr) [reply packages/shadydom/src/utils.js]: Added.

File: packages/tests/shadydom/event-path.html (hunk 12 above)
Comment (bicknellr) [reply packages/tests/shadydom/event-path.html]: I updated it so that it swaps descriptors for `eventPhase` (similar to existing code for `currentTarget`) when a listener on a shadow root is called. AFAICT, Shady DOM currently throws when dispatching to a shadow root itself, so I didn't handle that case. Also, the order is still wrong / depends on the order the listeners were added because listeners on shadow roots are actually added to their hosts, so they're all part of the same list. Fixing that seems like it's more effort than it's worth here / out of scope for this PR given most events go through native `dispatchEvent`.

File: packages/tests/shadydom/event-path.html [hunk 14]
```diff
@@ -999,17 +1125,25 @@
...
+          {currentTarget: ShadyDOM.wrap(fixtureRoot).shadowRoot, eventPhase: Event.CAPTURING_PHASE},
           {currentTarget: outerDiv, eventPhase: Event.CAPTURING_PHASE},
           {currentTarget: innerNoSlot, eventPhase: Event.CAPTURING_PHASE},
           {currentTarget: target, eventPhase: Event.AT_TARGET},
           {currentTarget: target, eventPhase: Event.AT_TARGET},
           {currentTarget: innerNoSlot, eventPhase: Event.BUBBLING_PHASE},
           {currentTarget: outerDiv, eventPhase: Event.BUBBLING_PHASE},
-          {currentTarget: outerNoSlot, eventPhase: Event.AT_TARGET},
+          {currentTarget: fixtureRoot, eventPhase: Event.AT_TARGET},
+          // The bubbling event listener on this shadow root is incorrectly run
```
Comment (sorvell) [inline packages/tests/shadydom/event-path.html:1137]: It's unclear why the order of running the event listeners should be wrong. Can you explain that?

Comment (bicknellr) [reply packages/tests/shadydom/event-path.html:1137]: When you add an event listener to a shadow root, the wrapper actually adds a (wrapped) listener to the shadow root's host:

https://github.com/webcomponents/polyfills/blob/9bd1fc0e13ba3c68d691ff7115397b6e735a8edc/packages/shadydom/src/patches/ShadowRoot.js#L21-L30

This way, even though Shady DOM's shadow roots aren't nodes in the real tree, their listeners will be still called by natively dispatched events. However, the order in which they're added ends up affecting when they're called because all the listeners added by the user to the host or its shadow root are all added to that host's single native list of listeners. For example, if bubbling listener A is first added to some host and then bubbling listener B is added to its shadow root, a bubbling, composed event dispatched to a node inside the shadow root will call A and then B because A was added first, even though B would normally be called first in a browser with native Shadow DOM.

Comment (sorvell) [reply packages/tests/shadydom/event-path.html:1137]: Ah, got it, that is not ideal but makes sense.
